// Configuring Environment
module.exports = [
  {
    name: "default",
    type: "mysql",
    port: 3306,
    host: "localhost",
    username: "matheus",
    password: "root",
    database: "vuttr_core",
    synchronize: true,
    logging: false,
    entities: ["dist/entities/*.js"],
    migrations: ["dist/migrations/*.js"],
  },
  {
    name: "test",
    type: "mysql",
    port: 3306,
    host: "localhost",
    username: "matheus",
    password: "root",
    database: "vuttr_core_test",
    synchronize: true,
    logging: false,
    entities: ["src/entities/*.ts", "dist/entities/*.js"],
    migrations: ["src/migrations/*.ts", "dist/migrations/*.js"],
    cli: {
      migrationsDir: "./src/migrations",
      entitiesDir: "./src/entities",
    },
  },
  {
    name: "development",
    type: "mysql",
    port: 3306,
    host: "localhost",
    username: "matheus",
    password: "root",
    database: "vuttr_core",
    synchronize: true,
    logging: false,
    entities: ["src/entities/*.ts", "dist/entities/*.js"],
    migrations: ["src/migrations/*.ts", "dist/migrations/*.js"],
    cli: {
      migrationsDir: "./src/migrations",
      entitiesDir: "./src/entities",
    },
  },
];
