openapi: 3.0.0

info:
  title: Vuttr Core
  description: The core service to the Very Useful Tools To Remind project.
  version: "1.0.0"
  contact:
    name: Matheus Figueirêdo
    email: matheussousaf.js@gmail.com
servers:
  - url: https://vuttr-core.herokuapp.com/v1
    description: Main URL for the VUTTR Core API (Production)
paths:
  /tools:
    get:
      summary: Returns a list of Tools.
      responses:
        "200": # status code
          description: A JSON array of all tools.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tool"

    post:
      summary: Create a new Tool.
      requestBody:
        description: A Tool object to be created.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToolDTO"
      responses:
        "201":
          description: Successfully created a new Tool.
        "500":
          description: Error trying to create a Tool.
  /tools/{id}:
    get:
      summary: Get a single Tool.
      parameters:
        - in: path
          required: true
          name: id
          description: The ID of the Tool.
          schema:
            type: integer
      responses:
        "200":
          description: Successfully fetched Tool.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToolDTO"
        "404":
          description: Tool not found.
        "500":
          description: Error fetching Tool.

    put:
      summary: Edit a Tool.
      parameters:
        - in: path
          required: true
          name: id
          description: The ID of the Tool which will be edited.
          schema:
            type: integer
      responses:
        "200":
          description: Successfully edited Tool.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToolDTO"
        "404":
          description: Tool not found.
        "500":
          description: Error editing Tool.

    delete:
      summary: Delete a Tool.
      parameters:
        - in: path
          required: true
          name: id
          description: The ID of the Tool which will be deleted.
          schema:
            type: integer
      responses:
        "204":
          description: Successfully deleted Tool.
        "404":
          description: Tool not found.
        "500":
          description: Error deleting Tool.

# Entities / Payload Objects
components:
  schemas:
    Tool:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        link:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string

    ToolDTO:
      type: object
      properties:
        title:
          type: string
        link:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
