openapi: 3.0.0

info:
  title: Vuttr Core
  description: The core service to the Vuttr project.
  version: "1.0.0"
  contact:
    name: Matheus Figueirêdo
    email: matheussousaf.js@gmail.com
servers:
  - url: https://vuttr-core.herokuapp.com/
    description: Main URL for the Vuttr Core API (Production)

paths:
  /tools:
    get:
      summary: Returns a list of Tools.
      responses:
        "200": # status code
          description: A JSON array of all tools.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tool"

    post:
      summary: Create a new Tool.
      requestBody:
        description: A Tool object to be created.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToolRequest"          
      responses:
        "201":
          description: Successfully created a new Tool.
        "500":
          description: Error trying to create a Tool.

    put:
      summary: Edits a existent Tool.
      parameters:
        - in: path
          required: true
          name: id
          description: The ID of the Tool which will be edited.
          schema: 
            type: integer
      responses:
        "200":
          description: Successfully edited Tool.
        "404":
          description: Tool not found.
        "500":
          description: Error editing Tool. 

        

# Entities / Payload Objects
components:
  schemas:
    Tool:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        link:
          type: string
        description:
          type: string
        tags:
          type: array
          items: 
            type: string
    
    ToolRequest:
      type: object
      properties:
        title:
          type: string
        link:
          type: string
        description:
          type: string
        tags:
          type: array
          items: 
            type: string