
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 12.x
        
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'vuttr_core_test' # Optional, default value is "test". The specified database which will be create
        mysql user: ${{ secrets.MYSQL_USER }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
    
    - name: Install dependencies
      run: yarn install
    
    - name: Run tests
      run: yarn test --watchAll false
    
    - name: Build image for the API
      run: docker build -t vuttr .
      
    - name: Build project (with docker compose)
      run: docker-compose up -d
    
    # TODO: Send to registry 
    
      
